name: Jana & Vasant
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Jana and Vasant Get Married
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3400d6'
    - '#e9e9eb'
    - '#131027'
    - '#b0b0b0'
    - '#0068d5'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
